// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TimeForPill.Data;

#nullable disable

namespace TimeForPill.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606200000_PacijentDnevneStatistike")]
    partial class PacijentDnevneStatistike
    {
    }
}
